{{- if .Values.mysql.embedded }}
apiVersion: v1
kind: Secret
metadata:
  name: batch-job-secret
type: Opaque
data:
  DATABASE_NAME: {{ .Values.mysql.auth.database | b64enc | quote }}
  DATABASE_USER: {{ .Values.mysql.auth.username | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  Environment: {{ .Values.secret.environment  | b64enc | quote }}
  {{- if .Values.mysql.embedded }}
  DB: {{ (printf "Server=%s-mysql.%s;Database=%s;Port=%d;Uid=%s;Pwd=%s;AllowUserVariables=True;" .Release.Name .Release.Namespace .Values.mysql.auth.database (int .Values.mysql.internal.port) .Values.mysql.auth.username .Values.mysql.auth.password) | b64enc | quote }}
  {{- else }}
  DB: {{ .Values.secret.dburl | b64enc | quote }}
  {{- end }}
{{- end }}
